---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.yaml: |
    ---
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    api:
      insecure: true
      dashboard: true
    ping:
      entryPoint: traefik

    entryPoints:
      traefik:
        address: ":9000"
      web:
        address: ":80"

      websecure:
        address: ":443"
    providers:
      kubernetesIngress:
        ingressClass: traefik

    certificatesResolvers:
      letsencrypt:
        acme:
          email: chung.k.tran@gmail.com
          storage: acme.json
          httpChallenge:
            entryPoint: web

    log:
      level: WARN
